SubscriptionID: 5959d188-3a85-4a68-98e0-af236b3c2cac
PolicyQueryASCPolicySetName:
PolicyQueryManagementGroupName:
OldBaselineExcelFilePath: test_resources/Azure Cloud Foundation - Baseline Policies.xlsx
ExcelFilePath: test_resources/Azure Cloud Foundation - Baseline Policies - WithUserInputs.xlsx
YAMLFilePath: test_resources/example_policies.yaml
LocalLandingZoneRepoDir: /Users/chszchen/Home/Temp/azure/ACF3.Modular
ManagementGroups:
  - ACF's subscriptions
  - PLATFORM's subscriptions
  - LANDING ZONE's subscriptions
  - SANDBOX's subscriptions
ASCParametersFileMappings:
  ACF's subscriptions: ASC_policy_ACF.json
  PLATFORM's subscriptions: ASC_policy_PLATFORM.json
  LANDING ZONE's subscriptions: ASC_policy_LANDINGZONE.json
  SANDBOX's subscriptions: ASC_policy_SANDBOX.json
