SubscriptionID: 5959d188-3a85-4a68-98e0-af236b3c2cac
PolicyQueryASCPolicySetName:
PolicyQueryManagementGroupName:
OldBaselineExcelFilePath: test_resources/Azure Cloud Foundation - Baseline Policies.xlsx
ExcelFilePath: test_resources/Azure Cloud Foundation - Baseline Policies - WithUserInputs.xlsx
LocalLandingZoneRepoDir: /Users/chszchen/Home/Temp/azure/ACF3.Modular
ManagementGroups:
  - aa subscriptions
  - bb's subscriptions
  - LANDING ZONE's subscriptions
  - another' subscription
  - SANDBOX's subscriptions
ASCParametersFileMappings:
  aa subscriptions: ASC_policy_aa.json
  bb's subscriptionss: ASC_policy_bb.json
  LANDING ZONE's subscriptions: ASC_policy_LANDINGZONE.json
  another' subscription: ASC_policy_another.json
  SANDBOX's subscriptions: ASC_policy_SANDBOX.json
