SubscriptionID:
PolicyQueryASCPolicySetName:
PolicyQueryManagementGroupName:
ExcelFilePath:
YAMLFilePath:
LocalLandingZoneRepoDir:
ManagementGroups:
  - Management
  - Production
  - Non-Prod
  - Sandbox