SubscriptionID: 5959d188-3a85-4a68-98e0-af236b3c2cac
PolicyQueryASCPolicySetName:
PolicyQueryManagementGroupName:
OldBaselineExcelFilePath: test_resources/Azure Cloud Foundation - Baseline Policies - October 2021.xlsx
ExcelFilePath: test_resources/Azure Cloud Foundation - Baseline Policies - WithUserInputs.xlsx
LocalLandingZoneRepoDir: /Users/chszchen/Home/Temp/azure/ACF3.Modular
ManagementGroups:
  - mg-acfdev
  - mg-platform
  - mg-landing-zone
  - mg-sandbox
Subscriptions:
  - Common for ACF's subscriptions
  - Specific requirement 1
  - Specific requirement 2
  - Specific requirement 3

# Support flexible values